name: Build OpenWrt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  schedule:
    - cron: 0 19 * * 1

env:
  USER_CONFIG: k2p

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: 初始化环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt update
        sudo apt -y install build-essential asciidoc binutils bzip2 \
             gawk gettext git libncurses5-dev libz-dev patch python3 \
             python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 \
             subversion flex uglifyjs git-core gcc-multilib p7zip \
             p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto \
             qemu-utils upx libelf-dev autoconf automake libtool \
             autopoint device-tree-compiler g++-multilib antlr3 gperf \
             wget curl swig rsync
        sudo timedatectl set-timezone "Asia/Shanghai"
        
    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@main
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false')

    - name: 克隆源码
      if: ${{ success() }}
      run: |
        git clone https://github.com/coolsnowwolf/lede.git

    - name: 自定义配置
      if: ${{ success() }}
      run: |
        cd lede
        sed -i 's/^#\(.*helloworld\)/\1/' feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig
        cp ../openwrt/$USER_CONFIG.config .config

    - name: 编译中...
      if: ${{ success() }}
      run: |
        cd lede
        make -j4 download
        make -j4 || make -j1 V=s
        echo "STATU=success" >> $GITHUB_ENV
        rm -rf bin/targets/*/*/packages
        echo "FILE_NAME=OpenWrt_${{ env.USER_CONFIG }}_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: 上传固件
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.FILE_NAME }}
        path: lede/bin/targets/*/*/*.bin

    - name: 上传固件至release
      if: ${{ success() }}
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.FILE_NAME }}
        files: lede/bin/targets/*/*/*.bin

    - name: 删除旧版固件
      if: ${{ success() }}
      uses: dev-drprasad/delete-older-releases@v0.1.0
      with:
        keep_latest: 4
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 微信推送
      run: |
        if [ "${{ env.STATU }}" == "success" ]; then
        curl https://sc.ftqq.com/${{ secrets.SCKEY }}.send?text=OpenWrt编译完成
        else 
        curl https://sc.ftqq.com/${{ secrets.SCKEY }}.send?text=OpenWrt编译失败
        fi
