name: Build Padavan

on: 
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  schedule:
    - cron: 20 20 * * 1

env:
  USER_CONFIG: K2P_nano-5.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: 初始化环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt update
        sudo apt -y install unzip libtool-bin curl cmake gperf gawk \
             flex bison nano xxd fakeroot kmod cpio git python-docutils \
             gettext automake autopoint texinfo build-essential help2man \
             pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev \
             libncurses5-dev libltdl-dev wget libc-dev-bin
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@main
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false')

    - name: 克隆源码
      if: ${{ success() }}
      run: |
        git clone --depth=1 https://github.com/hanwckf/rt-n56u.git /opt/rt-n56u

    - name: 配置toolchain
      if: ${{ success() }}
      run: |
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh

    - name: 自定义配置
      if: ${{ success() }}
      run: |
        cp padavan/$USER_CONFIG.config /opt/rt-n56u/trunk/configs/templates

    - name: 编译中...
      if: ${{ success() }}
      run: |
        cd /opt/rt-n56u/trunk
        ./clear_tree
        fakeroot ./build_firmware_modify $USER_CONFIG
        echo "STATU=success" >> $GITHUB_ENV
        echo "FILE_NAME=Padavan_${{ env.USER_CONFIG }}_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name : 上传固件
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.FILE_NAME }}
        path: /opt/rt-n56u/trunk/images/*.trx

    - name: 上传固件至release
      if: ${{ success() }}
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.FILE_NAME }}
        files: /opt/rt-n56u/trunk/images/*.trx

    - name: 删除旧版固件
      if: ${{ success() }}
      uses: dev-drprasad/delete-older-releases@v0.1.0
      with:
        keep_latest: 4
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 微信推送
      run: |
        if [ "${{ env.STATU }}" == "success" ]; then
        curl https://sc.ftqq.com/${{ secrets.SCKEY }}.send?text=Padavan编译完成
        else 
        curl https://sc.ftqq.com/${{ secrets.SCKEY }}.send?text=Padavan编译失败
        fi
